"""
Ejercicio 12
Calcular una nota aleatoria entre el 1 y el 10 inclusive, para luego mostrar un mensaje según el valor:

- 6, 7, 8, 9 y 10 ---&gt; Promoción directa, la nota es ...
- 4 y 5 ---&gt; Aprobado, la nota es ...
- 1, 2 y 3 ---&gt; Desaprobado, la nota es ...
"""